services:
  api:
    build: .
    container_name: myapp-api
    env_file: .env
    environment:
      DB_URL: sqlite+aiosqlite:///./data/app.db
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
